
name: dragonfistfitness
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  boxicons_flutter: ^1.1.0
  modal_progress_hud: ^0.1.3
  circular_countdown_timer: ^0.0.5
  tuple: ^1.0.3
  intl: ^0.16.1

  cupertino_icons: ^0.1.3
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Bungee
      fonts:
        - asset: fonts/Bungee-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: Royal_Knights
      fonts:
        - asset: fonts/Royal_Knights-Demo.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: Monserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf