import 'Workout.dart';
import 'package:tuple/tuple.dart';

class AbsWorkout extends Workout {
  List<Tuple2<String, int>> list = [
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
    Tuple2('DB Suitcase Carry LH', 30),
    Tuple2('DB Suitcase Carry RH', 30),
    Tuple2('Reverse Crunch', 30),
    Tuple2('Hollow Body Rocks', 30),
    Tuple2('Flutter Kicks', 30),
  ];

  AbsWorkout() {
    super.setList(list);
  }
}
