import 'package:dragonfistfitness/screens/workout_screens/workout_classes/Workout.dart';
import 'package:tuple/tuple.dart';

class BicepsWorkout extends Workout {
  List<Tuple2<String, int>> list = [
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
    Tuple2('DB Curl', 30),
    Tuple2('Band Hammer Curl', 30),
    Tuple2('DB Preacher Curl', 30),
    Tuple2('DB Dynamic Swing Curl', 30),
    Tuple2('Band Curl Hold', 30),
  ];

  BicepsWorkout() {
    super.setList(list);
  }
}
