import 'package:tuple/tuple.dart';
import 'Workout.dart';

class ChestWorkout extends Workout {
  List<Tuple2<String, int>> list = [
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
    Tuple2('Incline Pushups', 30),
  ];

  ChestWorkout() {
    super.setList(list);
  }
}
