import 'package:dragonfistfitness/screens/workout_screens/workout_classes/Workout.dart';
import 'package:tuple/tuple.dart';

class TricepsWorkout extends Workout {
  List<Tuple2<String, int>> list = [
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
    Tuple2('Close Grip Pushups', 30),
    Tuple2('Band Press Down', 30),
    Tuple2('Shallow Dips', 30),
    Tuple2('Seated Press Downs', 30),
    Tuple2('Overhead Band Extension', 30),
  ];

  TricepsWorkout() {
    super.setList(list);
  }
}
